### PR TITLE
Ability to configure remote api baseurl in npm scripts

### PR DESCRIPTION
**Pull request by ryandegruyter**
By default the base url for requests to the microservices dashboard server will be the domain address in the url bar.

If the server runs on a different address you can provide the **--standalone** flag to point to the  correct server adress

f.e.
development

```
npm run server -- --standalone=http://localhost:8080/
```

production

```
npm run build:prod -- --standalone=http://www.msd.io/
```

Related to #91

### CODE REVIEW

**Comment by andreasevers** [comment]
Can this be merged @ryandegruyter ?

**Comment by ryandegruyter** [comment]
should be good. Did you find the time to review @TYsewyn ?

**Comment by TYsewyn** [comment]
I quickly scanned over the changes and they should be good.
One thing that should be changed is the readme.
I think it'd be better if we copy/paste it from the existing readme file.

What do you think @andreasevers?

**Comment by TYsewyn** [comment]
Closed this issue in favor of a 2.0

**Pull request closed without merging**
